/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View_Form;

import DatabaseDaoImpl.User_DaoImpl;
import Enum.TypeGender;
import Enum.TypeNotification;
import Model.User;
import Services.CheckHandle;
import static Services.Notification.showMessage;
import java.awt.Cursor;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.xml.bind.DatatypeConverter;

/**
 *
 * @author couni
 */
public class Resigner extends javax.swing.JFrame {


    public Resigner() {
        initComponents();
    }

    private boolean CheckInput()
    {
        String user = txtUserName.getText().trim();
        String pass = String.valueOf(txtPass.getPassword()).trim();
        String fullName = txtFullName.getText().trim();
        String phone = txtPhone.getText().trim();
        String confirmPass = String.valueOf(txtConfirmPass.getPassword()).trim();
        boolean action = true;
        
        // Xử lí User
        if (user.equals("")) {
            txtUserName.setHelperText("Please input user name");
            txtUserName.grabFocus();
            action = false;
        }
        else
        {
            txtUserName.setHelperText("");
            txtUserName.grabFocus();
        }
        
        //Xử lí Pass
        if (pass.equals("")) {
            txtPass.setHelperText("Please input password");
            if (action) {
                txtPass.grabFocus();
            }
            action = false;
        }
        else
        {
            txtPass.setHelperText("");
        }
        
        //Xử lí FullName
        if(fullName.equals(""))
        {
            txtFullName.setHelperText("Please input full name");
            txtFullName.grabFocus();
            action = false;
        }
        else
        {
            txtFullName.setHelperText("");
        }
        
        //Xử lí Phone
        if(phone.equals(""))
        {
            txtPhone.setHelperText("Please input your number phone");
            txtPhone.grabFocus();
            action = false;
        }
        else if(!CheckHandle.isValidPhone(phone))
        {
            txtPhone.setHelperText("The phone number data you entered is not valid.");
            txtPhone.grabFocus();
            action = false;
        }
        else
        {
            txtPhone.setHelperText("");
        }
        
        //Xử lí COnfirmPass
        if (!confirmPass.equals(pass)) {
            txtConfirmPass.setHelperText("The confirmation password you entered does not match the password.");
            if (action) {
                txtConfirmPass.grabFocus();
            }
            action = false;
        }
        else
        {
            txtConfirmPass.setHelperText("");
        }
        return action;
    }
    
    private boolean Resigner() throws NoSuchAlgorithmException
    {
        //Ảnh mặc định của User 
        String UrlAvatar = "/Images/Avatar/avatarpatient.jpg";
        String username = txtUserName.getText().trim();
        String pass = String.valueOf(txtPass.getPassword()).trim();
        String fullName = txtFullName.getText().trim();
        String phone = txtPhone.getText().trim();
        Date now = new Date();
        User user_temp = new User();
        user_temp.setUserName(username);
        user_temp.setFullName(fullName);
        user_temp.setPhone(phone);
        user_temp.setEmail("");
        user_temp.setBirthday(now);
        user_temp.setAddress("");
        user_temp.setGender(TypeGender.Other.toString());
        user_temp.setAvartarUrl(UrlAvatar);
        //Mã hóa password
        MessageDigest md = MessageDigest.getInstance("MD5");
        md.update(pass.getBytes());
        byte[] digest = md.digest();
        String myHash = DatatypeConverter
                .printHexBinary(digest).toUpperCase();
        
        
        user_temp.setPassword(myHash);
        
        User_DaoImpl user_Dao = new User_DaoImpl();
        if(user_Dao.AddUser(user_temp)){
            showMessage("Đăng ký tài khoản thành công", TypeNotification.Success);
            return true;
        }
        return false;   
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imgclosed = new swing.Image.ImageAvatar();
        txtFullName = new swing.Field.TextField();
        jLabel1 = new javax.swing.JLabel();
        txtUserName = new swing.Field.TextField();
        txtPhone = new swing.Field.TextField();
        txtConfirmPass = new swing.Field.PasswordField();
        txtPass = new swing.Field.PasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonEdit1 = new swing.Button.ButtonEdit();
        jLabel3 = new javax.swing.JLabel();
        imgclosed1 = new swing.Image.ImageAvatar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(238, 238, 238));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(238, 238, 238));

        imgclosed.setBorderSize(0);
        imgclosed.setImage(new javax.swing.ImageIcon(getClass().getResource("/Images/icon/close.png"))); // NOI18N

        txtFullName.setBackground(new java.awt.Color(238, 238, 238));
        txtFullName.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        txtFullName.setLabelText("Full Name");

        jLabel1.setFont(new java.awt.Font("Giaza", 0, 100)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(89, 89, 89));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Minimalist");

        txtUserName.setBackground(new java.awt.Color(238, 238, 238));
        txtUserName.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        txtUserName.setLabelText("User Name");

        txtPhone.setBackground(new java.awt.Color(238, 238, 238));
        txtPhone.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        txtPhone.setLabelText("Number Phone");

        txtConfirmPass.setBackground(new java.awt.Color(238, 238, 238));
        txtConfirmPass.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        txtConfirmPass.setLabelText("Confirm Password");
        txtConfirmPass.setPreferredSize(new java.awt.Dimension(64, 61));
        txtConfirmPass.setShowAndHide(true);

        txtPass.setBackground(new java.awt.Color(238, 238, 238));
        txtPass.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        txtPass.setLabelText("Password");
        txtPass.setPreferredSize(new java.awt.Dimension(64, 61));
        txtPass.setShowAndHide(true);

        jLabel5.setFont(new java.awt.Font("Inter", 2, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(89, 89, 89));
        jLabel5.setText("@2023 April");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/slide/person_register.png"))); // NOI18N

        buttonEdit1.setBackground(new java.awt.Color(89, 89, 89));
        buttonEdit1.setText("Register");
        buttonEdit1.setBackgroundColor(new java.awt.Color(89, 89, 89));
        buttonEdit1.setBorderColor(new java.awt.Color(89, 89, 89));
        buttonEdit1.setColorHover(new java.awt.Color(89, 89, 89));
        buttonEdit1.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        buttonEdit1.setRadius(20);
        buttonEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEdit1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(89, 89, 89));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Login");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        imgclosed1.setBorderSize(0);
        imgclosed1.setImage(new javax.swing.ImageIcon(getClass().getResource("/Images/icon/close.png"))); // NOI18N
        imgclosed1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgclosed1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imgclosed1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imgclosed1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFullName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtConfirmPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(105, 105, 105))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(292, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(272, 272, 272))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(305, 305, 305))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel2)
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(imgclosed1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(imgclosed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtConfirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(39, 39, 39)
                .addComponent(jLabel5)
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgclosed1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(imgclosed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void imgclosed1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgclosed1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_imgclosed1MouseClicked

    private void imgclosed1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgclosed1MouseEntered
        // TODO add your handling code here:
        imgclosed.setImage(new ImageIcon(getClass().getResource("/Images/icon/closedhover.png")));
        imgclosed.setCursor(new Cursor(Cursor.HAND_CURSOR) {
        });
        repaint();
    }//GEN-LAST:event_imgclosed1MouseEntered

    private void imgclosed1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgclosed1MouseExited
        // TODO add your handling code here:
        imgclosed.setImage(new ImageIcon(getClass().getResource("/Images/icon/close.png")));
        repaint();
    }//GEN-LAST:event_imgclosed1MouseExited

    private void buttonEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEdit1ActionPerformed
        // TODO add your handling code here:
        if(CheckInput())
        {
            try {
                if(Resigner())
                {
                    new Login().setVisible(true);
                    // Close the interface of login
                    this.dispose();
                }
            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(Resigner.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_buttonEdit1ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);
        // Close the interface of login
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resigner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resigner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resigner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resigner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resigner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Button.ButtonEdit buttonEdit1;
    private swing.Image.ImageAvatar imgclosed;
    private swing.Image.ImageAvatar imgclosed1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private swing.Field.PasswordField txtConfirmPass;
    private swing.Field.TextField txtFullName;
    private swing.Field.PasswordField txtPass;
    private swing.Field.TextField txtPhone;
    private swing.Field.TextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
