/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Components;

import java.io.File;
import javax.swing.Icon;
import swing.Button.ButtonEdit;
import swing.Image.ImageAvatar;

/**
 *
 * @author couni
 */
public class ImageField extends javax.swing.JPanel {

    /**
     * Creates new form Image
     */
    private String NameFile;
    private File selectedFile = null;
    
    public ImageField() {
        initComponents();
    }
    
    public int getWidthImage()
    {
        return this.imageAvatar.getWidth();
    }
    
    public int getHeightImage()
    {
        return this.imageAvatar.getHeight();
    }
    
    public ImageAvatar getLabelImage()
    {
        return this.imageAvatar;
    }
    
    public ButtonEdit getButton()
    {
        return btnDelete;
    }
    
    public void setImage(Icon icon)
    {
        imageAvatar.setImage(icon);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDelete = new swing.Button.ButtonEdit();
        imageAvatar = new swing.Image.ImageAvatar();

        setOpaque(false);

        btnDelete.setBackground(new java.awt.Color(255, 51, 255));
        btnDelete.setText("Delete");
        btnDelete.setBackgroundColor(new java.awt.Color(255, 51, 255));
        btnDelete.setBorderColor(new java.awt.Color(255, 0, 255));
        btnDelete.setColorHover(new java.awt.Color(255, 51, 255));
        btnDelete.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        btnDelete.setRadius(15);

        imageAvatar.setBorderSize(0);
        imageAvatar.setImage(new javax.swing.ImageIcon(getClass().getResource("/Images/Avatar/avatarpatient.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(imageAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(imageAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Button.ButtonEdit btnDelete;
    private swing.Image.ImageAvatar imageAvatar;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the NameFile
     */
    public String getNameFile() {
        return NameFile;
    }

    /**
     * @param NameFile the NameFile to set
     */
    public void setNameFile(String NameFile) {
        this.NameFile = NameFile;
    }

    /**
     * @return the selectedFile
     */
    public File getSelectedFile() {
        return selectedFile;
    }

    /**
     * @param selectedFile the selectedFile to set
     */
    public void setSelectedFile(File selectedFile) {
        this.selectedFile = selectedFile;
    }

}
