/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swing.TableBuild;

/**
 *
 * @author couni
 */
public class Badge extends javax.swing.JPanel {

    /**
     * Creates new form Badge
     * @param data
     */
    public Badge(ModelBadge data) {
        initComponents();
        txtBadgeName.setText(data.getBadgeName());
        txtBadgeName.setForeground(data.getTextColor());
        txtBadgeName.setBackground(data.getBackground());
        txtBadgeName.setBorderColor(data.getTextColor());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBadgeName = new swing.Badge.Badge();

        txtBadgeName.setText("Huy Hiệu");
        txtBadgeName.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        txtBadgeName.setRadius(25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBadgeName, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBadgeName, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Badge.Badge txtBadgeName;
    // End of variables declaration//GEN-END:variables
}
