/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Form;

import DatabaseDao.User_Dao;
import DatabaseDaoImpl.User_DaoImpl;
import Enum.TypeRoleName;
import Form.SlideForm.*;
import Model.User;
import com.raven.chart.ModelChartLine;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import jiconfont.icons.google_material_design_icons.GoogleMaterialDesignIcons;
import jiconfont.swing.IconFontSwing;
import javax.swing.JLayeredPane;
import swing.TableBuild.EventAction;
import swing.TableBuild.EventAction_Main;
/**
 *
 * @author couni
 */
public class Dashboard extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    private User user;
    private JLayeredPane body;
    public Dashboard() {
        initComponents();
        slideshow1.initSlideshow(new Slide1(), new Slide2(), new Slide3(), new Slide4());
        table1.fixTable(jScrollPane1);
        initTableData();
        initDataLine();
    }
    
    public Dashboard(JLayeredPane main, User user)
    {
        initComponents();
        this.body = main;
        this.user = user;
        DataUser();
        slideshow1.initSlideshow(new Slide1(), new Slide2(), new Slide3(), new Slide4());
        table1.fixTable(jScrollPane1);
        initTableData();
        initDataLine();
    }
    
    private void DataUser()
    {
        IconFontSwing.register(GoogleMaterialDesignIcons.getIconFont());
        headerBody1.init(null, 
                this.user, "Dashboard", null, this.body);
    }
    
    private void initTableData() {
        EventAction eventAction = new EventAction_Main(this.body, this.table1, user);
        //int i = 1;
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("       #");
        model.addColumn("Họ Và Tên");
        model.addColumn("Giới Tính");
        model.addColumn("Số Điện Thoại");
        model.addColumn("Chức Vụ");
        model.addColumn("Chức Năng");
        User_Dao users = new User_DaoImpl();
        ArrayList<User> userlist = users.getUserList(new User(null, TypeRoleName.None.toString()));
        for(User object : userlist)
        {
            model.addRow(new User(object).toRowTable(eventAction));
        }
        
//        model.addRow(new User(new ImageIcon(getClass().getResource("/Images/Avatar/avatar.jpg")), "Trần Cao Minh Thắng", "Male", "Admin", i++, "1").toRowTable(eventAction));

        table1.setModel(model);
        table1.setDefaultEditor(Object.class, null);
    }
    
    
    private void initDataLine() {

        //  Test data chart line
        List<ModelChartLine> list = new ArrayList<>();
        list.add(new ModelChartLine("Monday", 10));
        list.add(new ModelChartLine("Tuesday", 150));
        list.add(new ModelChartLine("Wednesday", 80));
        list.add(new ModelChartLine("Thursday", 100));
        list.add(new ModelChartLine("Friday", 125));
        list.add(new ModelChartLine("Saturday", 80));
        list.add(new ModelChartLine("Sunday", 200));
        chartLine1.setModel(list);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new swing.Panel.PanelBorder();
        cardDashboard1 = new swing.Card.CardDashboard();
        cardDashboard2 = new swing.Card.CardDashboard();
        cardDashboard4 = new swing.Card.CardDashboard();
        chartLine1 = new com.raven.chart.ChartLine();
        slideshow1 = new swing.SlideShow.Slideshow();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new swing.TableBuild.Table();
        jLabel2 = new javax.swing.JLabel();
        headerBody1 = new Components.HeaderBody();

        setOpaque(false);

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));
        panelBorder1.setForeground(new java.awt.Color(132, 132, 132));

        cardDashboard1.setColor1(new java.awt.Color(219, 226, 250));
        cardDashboard1.setColor2(new java.awt.Color(173, 189, 240));

        cardDashboard2.setColor1(new java.awt.Color(245, 192, 180));
        cardDashboard2.setColor2(new java.awt.Color(240, 126, 100));

        cardDashboard4.setColor1(new java.awt.Color(252, 228, 208));
        cardDashboard4.setColor2(new java.awt.Color(251, 183, 122));

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chartLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(cardDashboard4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cardDashboard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cardDashboard2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cardDashboard4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardDashboard2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardDashboard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(chartLine1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        slideshow1.setBackground(new java.awt.Color(255, 255, 255));

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Profile", "Họ Và Tên", "Giới Tính", "Số Điện Thoại", "Chức Vụ", "Chức Năng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table1);

        jLabel2.setFont(new java.awt.Font("Inter", 1, 26)); // NOI18N
        jLabel2.setText("Employee List");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headerBody1, javax.swing.GroupLayout.DEFAULT_SIZE, 942, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(slideshow1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerBody1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(slideshow1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Card.CardDashboard cardDashboard1;
    private swing.Card.CardDashboard cardDashboard2;
    private swing.Card.CardDashboard cardDashboard4;
    private com.raven.chart.ChartLine chartLine1;
    private Components.HeaderBody headerBody1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private swing.Panel.PanelBorder panelBorder1;
    private swing.SlideShow.Slideshow slideshow1;
    private swing.TableBuild.Table table1;
    // End of variables declaration//GEN-END:variables

}
