/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Form.Product;

import DatabaseDao.Category_Dao;
import DatabaseDaoImpl.Category_DaoImpl;
import Model.Categories;
import Model.User;

/**
 *
 * @author YAN
 */
public class OverView extends javax.swing.JPanel {

    private User user;
    public OverView() {
        initComponents();
    }
    
    public OverView(User user) {
        initComponents();
        this.user = user;
    }
    
    private void CreateCategory(){
        Categories category = new Categories();
        category.setCategoriesName(txtName.getText());
        category.setDescription(txtDescription.getText());
        
        Category_Dao category_Dao = new Category_DaoImpl();
        category_Dao.AddCategory(category);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonEdit1 = new swing.Button.ButtonEdit();
        txtName = new swing.Field.TextFieldRadius();
        textAreaScroll1 = new swing.Field.TextAreaScroll();
        txtDescription = new swing.Field.TextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setOpaque(false);

        buttonEdit1.setBackground(new java.awt.Color(23, 34, 56));
        buttonEdit1.setText("Save");
        buttonEdit1.setBackgroundColor(new java.awt.Color(23, 34, 56));
        buttonEdit1.setBorderColor(new java.awt.Color(0, 0, 0));
        buttonEdit1.setColorHover(new java.awt.Color(23, 34, 56));
        buttonEdit1.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        buttonEdit1.setRadius(10);
        buttonEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEdit1ActionPerformed(evt);
            }
        });

        txtName.setText("Input Name");
        txtName.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        txtName.setLabelText("Input Name");
        txtName.setRound(15);
        txtName.setShadowSize(new java.awt.Insets(1, 1, 1, -3));

        textAreaScroll1.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        textAreaScroll1.setLabelText("Description");

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        txtDescription.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        textAreaScroll1.setViewportView(txtDescription);

        jLabel6.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        jLabel6.setText("Category's Description");

        jLabel7.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        jLabel7.setText("Category's Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(buttonEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textAreaScroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textAreaScroll1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(buttonEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEdit1ActionPerformed
        CreateCategory();
    }//GEN-LAST:event_buttonEdit1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Button.ButtonEdit buttonEdit1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private swing.Field.TextAreaScroll textAreaScroll1;
    private swing.Field.TextArea txtDescription;
    private swing.Field.TextFieldRadius txtName;
    // End of variables declaration//GEN-END:variables
}
