/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ViewForm;

import DatabaseAccessObject_Impl.Staff_DaoImpl;
import Dialog.Swal_Notification;
import Enum.TypeNotification;
import Model.Employee;
import javax.swing.JOptionPane;

/**
 *
 * @author couni
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
    }

    
    public boolean validateLogin(){
        String userName = txt_username.getText();
        String pass = String.valueOf(txt_password.getPassword()).trim();;
        
        if(userName.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please enter your UserName");
            return false;
        }
        if(pass.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please enter your UserName");
            return false;
        }
        return true;
    }
    
    
    public void Login()
    {
        String userName = txt_username.getText().trim();
        String pass = String.valueOf(txt_password.getPassword()).trim();;
        Employee staff_temp = new Employee();
        staff_temp.setUserName(userName);
        staff_temp.setPassword(pass);
        
        Staff_DaoImpl staff_Dao = new Staff_DaoImpl();
        Employee staff = staff_Dao.Login_Staff(staff_temp);
        //System.out.println(staff.getFullName());
        if(staff == null)
        {
            showMessage("The user or pass is error.", TypeNotification.Error);
        }
        else
        {
            showMessage("Welcome : "  + staff.getRoleName() + " " /*+ UserType_selectItem*/ + " : "
						+ staff.getFullName(), TypeNotification.Success);
            new Main(staff).setVisible(true); //--> Đây là khỏi tạo giao diện chính thong qua người dùng
            // Close the interface of login
            this.dispose();
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        jLabelPassword = new javax.swing.JLabel();
        jLabelAccount = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        imgAvatar1 = new Swing.Img.ImgAvatar();
        button21 = new Swing.Button.Button2();
        imgAvatar2 = new Swing.Img.ImgAvatar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(79, 98, 203));
        jLabel3.setText("E Heatlth Care Management System");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 230, -1, -1));

        txt_username.setBackground(new java.awt.Color(246, 250, 255));
        txt_username.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txt_username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 98, 203), 3));
        txt_username.setSelectedTextColor(new java.awt.Color(246, 250, 255));
        txt_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_usernameFocusLost(evt);
            }
        });
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 360, 350, 50));

        jLabelPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(79, 98, 203));
        jLabelPassword.setText("Password");
        jPanel1.add(jLabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 420, -1, -1));

        jLabelAccount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelAccount.setForeground(new java.awt.Color(79, 98, 203));
        jLabelAccount.setText("Account");
        jPanel1.add(jLabelAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 310, -1, -1));

        txt_password.setBackground(new java.awt.Color(246, 250, 255));
        txt_password.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txt_password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 98, 203), 3));
        jPanel1.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 470, 350, 50));

        imgAvatar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login/BackgroundLogin.png"))); // NOI18N
        jPanel1.add(imgAvatar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 160, 830, 789));

        button21.setText("Login");
        button21.setRadius(40);
        button21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button21ActionPerformed(evt);
            }
        });
        jPanel1.add(button21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 540, 145, 37));

        imgAvatar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login/Logo.png"))); // NOI18N
        jPanel1.add(imgAvatar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 150, 70, 74));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1516, 813));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void txt_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameFocusLost

    private void button21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button21ActionPerformed
        // TODO add your handling code here:
        validateLogin();
        Login();
    }//GEN-LAST:event_button21ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }
    
    private boolean showMessage(String message, TypeNotification type) {
        Swal_Notification obj = new Swal_Notification(LoginForm.getFrames()[0], true);
        obj.showMessage(message, type);
        return obj.isOk();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Swing.Button.Button2 button21;
    private Swing.Img.ImgAvatar imgAvatar1;
    private Swing.Img.ImgAvatar imgAvatar2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAccount;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
