/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AdminForm;

/**
 *
 * @author Admin
 */
public class InfomationProfile extends javax.swing.JPanel {

    /**
     * Creates new form InfomationProfile
     */
    public InfomationProfile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleTable = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        TitleTable1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        button21 = new Swing.Button.Button2();

        setForeground(new java.awt.Color(79, 98, 203));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitleTable.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        TitleTable.setText("History");
        add(TitleTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 586, 133, 43));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/Group 31.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 15, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/Group 44.png"))); // NOI18N
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 40, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Avatar/Rectangle 43341.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 112, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(79, 98, 203));
        jLabel3.setText("IDStaff:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 112, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(79, 98, 203));
        jLabel4.setText("Name:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 187, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(79, 98, 203));
        jLabel5.setText("Phone Number:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 262, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(79, 98, 203));
        jLabel6.setText("CCCD/CMND:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 262, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(79, 98, 203));
        jLabel7.setText("Bitrthday: (dd/mm/yyyy)");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 187, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(79, 98, 203));
        jLabel8.setText("Position:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 112, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(79, 98, 203));
        jLabel9.setText("Sex:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(785, 187, -1, -1));

        jTextField1.setBackground(new java.awt.Color(238, 245, 255));
        jTextField1.setColumns(1);
        jTextField1.setForeground(new java.awt.Color(79, 98, 203));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField1.setText("DR001");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(126, 175, 255), 2));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 134, 247, 47));
        jTextField1.getAccessibleContext().setAccessibleName("");

        jTextField2.setBackground(new java.awt.Color(238, 245, 255));
        jTextField2.setColumns(1);
        jTextField2.setForeground(new java.awt.Color(79, 98, 203));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField2.setText("Customer Name");
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(126, 175, 255), 2));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 209, 247, 47));

        jTextField3.setBackground(new java.awt.Color(238, 245, 255));
        jTextField3.setColumns(1);
        jTextField3.setForeground(new java.awt.Color(79, 98, 203));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField3.setText("0922113123");
        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(126, 175, 255), 2));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 284, 247, 47));

        jComboBox1.setBackground(new java.awt.Color(238, 245, 255));
        jComboBox1.setForeground(new java.awt.Color(79, 98, 203));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Member" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(126, 175, 255), 2));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 134, 269, 47));

        jTextField4.setBackground(new java.awt.Color(238, 245, 255));
        jTextField4.setColumns(1);
        jTextField4.setForeground(new java.awt.Color(79, 98, 203));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField4.setText("20/02/2002");
        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(126, 175, 255), 2));
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 209, 269, 47));

        jTextField5.setBackground(new java.awt.Color(238, 245, 255));
        jTextField5.setColumns(1);
        jTextField5.setForeground(new java.awt.Color(79, 98, 203));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField5.setText("0192131244234");
        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(126, 175, 255), 2));
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 284, 269, 47));

        jComboBox2.setBackground(new java.awt.Color(238, 245, 255));
        jComboBox2.setForeground(new java.awt.Color(79, 98, 203));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jComboBox2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(126, 175, 255), 2));
        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(785, 209, 178, 47));

        jTextField6.setBackground(new java.awt.Color(238, 245, 255));
        jTextField6.setColumns(1);
        jTextField6.setForeground(new java.awt.Color(79, 98, 203));
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField6.setText("141 Dien Bien Phu, Binh Thanh, Ho Chi Minh ");
        jTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(126, 175, 255), 2));
        add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 365, 532, 47));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(79, 98, 203));
        jLabel10.setText("Address:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 343, -1, -1));

        jTextField7.setBackground(new java.awt.Color(238, 245, 255));
        jTextField7.setColumns(1);
        jTextField7.setForeground(new java.awt.Color(79, 98, 203));
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField7.setText("Ho Chi Minh, Viet Nam");
        jTextField7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(126, 175, 255), 2));
        add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 440, 532, 47));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(79, 98, 203));
        jLabel11.setText("Place of birth:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 418, -1, -1));

        jTextField8.setBackground(new java.awt.Color(238, 245, 255));
        jTextField8.setColumns(1);
        jTextField8.setForeground(new java.awt.Color(79, 98, 203));
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField8.setText("khanhhlg20@gmail.com");
        jTextField8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(126, 175, 255), 2));
        add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 521, 532, 47));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(79, 98, 203));
        jLabel12.setText("Email:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 499, -1, -1));

        TitleTable1.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        TitleTable1.setText("Edit Doctor");
        add(TitleTable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 16, 379, 43));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(79, 98, 203));
        jLabel13.setText("Date");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 635, -1, -1));

        jTextField9.setBackground(new java.awt.Color(238, 245, 255));
        jTextField9.setColumns(1);
        jTextField9.setForeground(new java.awt.Color(79, 98, 203));
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField9.setText("20/02/2002");
        jTextField9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(126, 175, 255), 2));
        add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 657, 160, 47));

        jTextField10.setBackground(new java.awt.Color(238, 245, 255));
        jTextField10.setColumns(1);
        jTextField10.setForeground(new java.awt.Color(79, 98, 203));
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(126, 175, 255), 2));
        add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 657, 532, 47));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(79, 98, 203));
        jLabel14.setText("Event");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 635, -1, -1));

        button21.setBackground(new java.awt.Color(79, 98, 203));
        button21.setForeground(new java.awt.Color(255, 255, 255));
        button21.setText("Save");
        button21.setRadius(15);
        add(button21, new org.netbeans.lib.awtextra.AbsoluteConstraints(865, 657, 98, 47));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TitleTable;
    private javax.swing.JLabel TitleTable1;
    private Swing.Button.Button2 button21;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
